version: '3.8'

services:
  recomapp:
    build: .
    container_name: rec_collection_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx_proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - app
  #   restart: always
